# use the correct architecture (x-86-64 / arm64)
FROM public.ecr.aws/lambda/python:3.9-x86_64

ADD app app

COPY ./requirements.txt ./requirements.txt

RUN pip install -r ./requirements.txt

ENV TRANSFORMERS_CACHE=/tmp

# project_folder.py_file.mangum_object_name
CMD ["app.main.handler"]